-- Datos iniciales del CRM: 270 empresas de Misiones con email publicado (ver empresas-misiones.md).
-- Correr DESPUÉS de 20261010000001_crm_empresas.sql. Se puede volver a correr: los emails repetidos se ignoran.

insert into public.empresas (nombre, rubro, zona, email, web, tamano, fuente, notas)
values
  ('Labandoczka Orlando Fabian', 'Comercio / ferretería / agro', '25 de Mayo', 'labandoczka_ventas@hotmail.com', null, 'pyme', 'Rumbo', ''),
  ('De Olivera Cristian Ed.', 'Transporte y logística', '25 de Mayo', 'cri-se@hotmail.com', null, 'pyme', 'Global Invest', ''),
  ('Fasciszewski Evaristo Alfonso', 'Comercio / ferretería / agro', 'Apóstoles', 'agrovetsanantonio@yahoo.com.ar', null, 'pyme', 'Rumbo', ''),
  ('Rodriguez Luis Alberto', 'Comercio / ferretería / agro', 'Apóstoles', 'agroymotosierras@yahoo.com.ar', null, 'pyme', 'Rumbo', ''),
  ('Do Santos Jose Omar', 'Comercio / ferretería / agro', 'Aristóbulo del Valle', 'tiendasomar@hotmail.com.ar', null, 'pyme', 'Rumbo', ''),
  ('BRÍGODP ORLANDO OBREGÓN', 'Despachante de aduana', 'Bernardo de Irigoyen', 'obregon_dc@hotmail.com', null, 'pyme', 'Global Invest', ''),
  ('Cieplinski Susana', 'Comercio / ferretería / agro', 'Campo Grande', 'susanacieplinski@yahoo.com.ar', null, 'pyme', 'Rumbo', ''),
  ('Capell Fideicomiso', 'Té', 'Campo Grande', 'diegohm@hotmail.com', null, 'pyme', 'Global Invest', ''),
  ('Fontana S.A', 'Té', 'Campo Grande', 'fontana3362@yahoo.com.ar', null, 'pyme', 'Global Invest', ''),
  ('Corteza S.R.L', 'Forestal / maderera', 'Campo Ramón', 'emilio@familiajuritsch.com', null, 'pyme', 'Global Invest', ''),
  ('Martín Bauer Argentina S.A', 'Té', 'Campo Ramón', 'renzo.chini@martin-bauer.com', 'https://martin-bauer.com', 'grande', 'Global Invest', ''),
  ('El Colono de Campo Ramón', 'Yerba mate', 'Campo Ramón', 'comercioexterior@grapiamilenaria.com.ar', 'https://www.grapiamilenaria.com.ar', 'pyme', 'Global Invest', ''),
  ('MyAgro Ferretería Agroindustrial', 'Comercio / ferretería / agro', 'Campo Viera', 'cristian90mysliwczuk@gmail.com', null, 'pyme', 'Rumbo', ''),
  ('Doña Irma', 'Té', 'Campo Viera', 'irmafraga62@gmail.com', null, 'pyme', 'Catálogo té', ''),
  ('Klimiuk Hermanos S.R.L', 'Té', 'Campo Viera', 'gerencia@klimiukinfusiones.com', 'https://klimiukinfusiones.com', 'pyme', 'Global Invest', ''),
  ('CHAM Sociedad Colectiva', 'Comercio / ferretería / agro', 'Capioví', 'chamcapiovi@gmail.com', null, 'pyme', 'Rumbo', ''),
  ('PROCAYPA', 'Comercio / ferretería / agro', 'Capioví', 'celsolimberger@yahoo.com.ar', null, 'pyme', 'Rumbo', ''),
  ('Stang César Daniel', 'Transporte y logística', 'Capioví', 'cesardanielstang@gmail.com', null, 'pyme', 'Global Invest', ''),
  ('Selva Y Monte Experience', 'Turismo aventura', 'Capioví', 'sebastiankcres@hotmail.com', null, 'pyme', 'Registro turismo', ''),
  ('Agroazul', 'Comercio / ferretería / agro', 'Cerro Azul', 'agropecuaria@agroazul.com.ar', null, 'pyme', 'Rumbo', ''),
  ('Punto Nea SRL', 'Comercio / ferretería / agro', 'Cerro Azul', 'compraspuntonea@gmail.com', null, 'pyme', 'Rumbo', ''),
  ('Smiguel Luis Carlos', 'Comercio / ferretería / agro', 'Cerro Azul', 'gestion.smiguel@gmail.com', null, 'pyme', 'Rumbo', ''),
  ('Smiguel, Cristian Ivan', 'Comercio / ferretería / agro', 'Cerro Azul', 'smiguelhermanos@gmail.com', null, 'pyme', 'Rumbo', ''),
  ('Aserradero Sauer S.R.L', 'Forestal / maderera', 'Cerro Azul', 'aserrasauer@gmail.com', 'https://www.serraderosauer.com.ar', 'pyme', 'Global Invest', ''),
  ('Finca Don Ramón- Smichowski Silvia Maria Andrea', 'Turismo aventura', 'Cerro Corá', 'smichowskia@gmail.com', null, 'pyme', 'Registro turismo', ''),
  ('AGRO-FORRAJERIA MISIONES - Diaz Douglas Mateo', 'Comercio / ferretería / agro', 'Colonia Aurora', 'jostcarlabeatriz@gmail.com.ar', null, 'pyme', 'Rumbo', ''),
  ('(sin nombre en el listado) glienkelean', 'Transporte y logística', 'Colonia Aurora', 'glienkelean@gmail.com', null, 'pyme', 'Global Invest', ''),
  ('Díaz Douglas Mateo', 'Transporte y logística', 'Colonia Aurora', 'diazdouglas1991@gmail.com', null, 'pyme', 'Global Invest', ''),
  ('Alma Annette', 'Té', 'Colonia Guaraní', 'almaannette.guarani@gmail.com', null, 'pyme', 'Catálogo té', ''),
  ('Cooperativa Agrícola Colonia Liebig', 'Yerba mate', 'Colonia Liebig (Corrientes)', 'atconsumidores@cooperativaliebig.com.ar', 'https://cooperativaliebig.com.ar', 'pyme', 'Sitio oficial', ''),
  ('GP Energy S.A', 'Forestal / maderera', 'Colonia Victoria', 'gerencia@gpenergy.com.ar', 'https://www.gpenergy.com.ar', 'grande', 'Global Invest', ''),
  ('Fibercom SRL', 'Comercio / ferretería / agro', 'Comandante Andresito', 'comercial@proyectamas.ar', null, 'pyme', 'Rumbo', ''),
  ('Harter Bruno Eduardo', 'Comercio / ferretería / agro', 'Comandante Andresito', 'agropecuariamisiones@hotmail.com', null, 'pyme', 'Rumbo', ''),
  ('Turismo Tierra Verde', 'Turismo aventura', 'Comandante Andresito', 'turismotierraverde@hotmail.com', null, 'pyme', 'Registro turismo', ''),
  ('Coop. Yerbatera Andresito Limitada', 'Yerba mate', 'Comandante Andresito', 'pablo@yerbaandresito.com.ar', 'https://www.yerbaandresito.com.ar', 'pyme', 'Global Invest', ''),
  ('Forestal y Ganadera Indumarca S.A', 'Forestal / maderera', 'Concepción de la Sierra', 'atencionalcliente.fygisa@gmail.com', 'https://www.fygisa.com.ar', 'pyme', 'Global Invest', ''),
  ('Marilyn Travel Evt', 'Turismo aventura', 'Corpus', 'marilyntravel.evt@gmail.com', null, 'pyme', 'Registro turismo', ''),
  ('Cuña Pirú Lodge', 'Hotel / lodge', 'Cuña Pirú', 'reservas@cunapirulodge.com', 'https://cunapirulodge.com', 'pyme', 'Sitio oficial', ''),
  ('Weber Yanina Andrea', 'Comercio / ferretería / agro', 'Dos de Mayo', 'lawerferreteria@gmail.com', null, 'pyme', 'Rumbo', ''),
  ('Placas Rivadavia S.R.L', 'Forestal / maderera', 'Dos de Mayo', 'recepcionplacasrivadavia@gmail.com', 'https://www.placasrivadaviasrl.com.ar', 'pyme', 'Global Invest', ''),
  ('(sin nombre en el listado) gasparaguerre', 'Transporte y logística', 'Dos de Mayo', 'gasparaguerre@hotmail.com', null, 'pyme', 'Global Invest', ''),
  ('Kiernoga Cristian Alej.', 'Transporte y logística', 'Dos de Mayo', 'distribuidora_felik@outlook.es', null, 'pyme', 'Global Invest', ''),
  ('Coop. Yerbatera Dos de Mayo', 'Té', 'Dos de Mayo', 'yerbamateindumar@gmail.com', 'https://www.yerbaindumar.com', 'pyme', 'Global Invest', ''),
  ('Valmitran S.A', 'Té', 'Dos de Mayo', 'egoldfart@valmitran.com', 'https://valmitran.com', 'pyme', 'Global Invest', ''),
  ('Grupo Fortezza S.R.L', 'Yerba mate', 'Dos de Mayo', 'contacto@asdebastos.com.ar', 'https://www.asdebastos.com.ar', 'pyme', 'Global Invest', ''),
  ('Simacon S.A', 'Construcción', 'El Alcazar', 'info@simacon.com.ar', 'https://simacon.com.ar', 'pyme', 'Global Invest', ''),
  ('Yacaratiá Delicatessen', 'Gastronomía', 'El Soberbio', 'info@yacaratia.com', 'https://yacaratia.com', 'pyme', 'Sitio oficial', ''),
  ('Hostel Y Cabañas Buena Vista', 'Hotel', 'El Soberbio', 'cabaniasbuenavista@gmail.com', null, 'pyme', 'Registro turismo', ''),
  ('Guaviroba Rappel', 'Turismo aventura', 'El Soberbio', 'matibreeder@gmail.com', null, 'pyme', 'Registro turismo', ''),
  ('La Perla De La Selva Turismo Aventura', 'Turismo aventura', 'El Soberbio', 'experiencemocona@gmail.com', null, 'pyme', 'Registro turismo', ''),
  ('Mbojere Excursiones Guiadas', 'Turismo aventura', 'El Soberbio', 'mbojereexcursiones@gmail.com', null, 'pyme', 'Registro turismo', ''),
  ('Albura Agroinsumos - Garcia Natalia', 'Comercio / ferretería / agro', 'Eldorado', 'nataliagarcia1505@gmail.com', null, 'pyme', 'Rumbo', ''),
  ('Albura Agroinsumos - GED', 'Comercio / ferretería / agro', 'Eldorado', 'ventas@albura.com', null, 'pyme', 'Rumbo', ''),
  ('Wallisch Francisco José', 'Comercio / ferretería / agro', 'Eldorado', 'franwall@arnet.com.ar', null, 'pyme', 'Rumbo', ''),
  ('Establecimiento Don Guillermo S.R.L', 'Forestal / maderera', 'Eldorado', 'ventas@donguillermosrl.com.ar', 'https://donguillermosrl.com.ar', 'pyme', 'Global Invest', ''),
  ('Forestal Eldorado S.R.L', 'Forestal / maderera', 'Eldorado', 'info@forestaleldorado.com.ar', 'https://www.forestaleldorado.com.ar', 'pyme', 'Global Invest', ''),
  ('Fundador S.R.L', 'Forestal / maderera', 'Eldorado', 'fundadorsrl@arnetbiz.com.ar', null, 'pyme', 'Global Invest', ''),
  ('Toll Maderas S.R.L', 'Forestal / maderera', 'Eldorado', 'toll.maderas.srl@gmail.com', 'https://www.tollmaderas.com', 'pyme', 'Global Invest', ''),
  ('Faszzeki Maquinas Para Madera S.R.L', 'Metalmecánica', 'Eldorado', 'eldocontable@yahoo.com.ar', 'https://www.faszzeskimaquinas.com', 'pyme', 'Global Invest', ''),
  ('Almuzara Sebastián Alfr.', 'Transporte y logística', 'Eldorado', 'sebastianalmuzara@hotmail.com', null, 'pyme', 'Global Invest', ''),
  ('Bencina Luis Eduardo', 'Transporte y logística', 'Eldorado', 'bencinaluis@hotmail.com', null, 'pyme', 'Global Invest', ''),
  ('Chamorro Héctor Fabián', 'Transporte y logística', 'Eldorado', 'danielduran@selvasrl.net', null, 'pyme', 'Global Invest', ''),
  ('Fechner Gabriel', 'Transporte y logística', 'Eldorado', 'automotoresap@gmail.com', null, 'pyme', 'Global Invest', ''),
  ('Horrisberger Oscar Fer.', 'Transporte y logística', 'Eldorado', 'oscarhorris@gmail.com', null, 'pyme', 'Global Invest', ''),
  ('Jelen Marco Alexander', 'Transporte y logística', 'Eldorado', 'marco@bracia.com.ar', null, 'pyme', 'Global Invest', ''),
  ('Knobel Federico', 'Transporte y logística', 'Eldorado', 'cristian_knobel@hotmail.com', null, 'pyme', 'Global Invest', ''),
  ('Lizzul Vanesa Pamela', 'Transporte y logística', 'Eldorado', 'pamelalizzul@gmail.com', null, 'pyme', 'Global Invest', ''),
  ('Mut Vicente Alfonso', 'Transporte y logística', 'Eldorado', 'transjosemaria-eldo@hotmail.com.ar', null, 'pyme', 'Global Invest', ''),
  ('Neumann Omar', 'Transporte y logística', 'Eldorado', 'omarneumann@arnet.com.ar', null, 'pyme', 'Global Invest', ''),
  ('Reihle Sebastián', 'Transporte y logística', 'Eldorado', 'sreihle@reihlehermanos.com', null, 'pyme', 'Global Invest', ''),
  ('Trendel Gabriel', 'Transporte y logística', 'Eldorado', 'trendel_gabriel@hotmail.com', null, 'pyme', 'Global Invest', ''),
  ('Haras Itapé', 'Turismo aventura', 'Fachinal', 'rlacona@ibera-argentina.com', null, 'pyme', 'Registro turismo', ''),
  ('Vogel Sergio Omar', 'Transporte y logística', 'Garuhapé', 'sergioomarvogel75@gmail.com', null, 'pyme', 'Global Invest', ''),
  ('Valerio Oliva Forestal S.A', 'Forestal / maderera', 'Garupá', 'silvina@valerioolivaforestal.com.ar', 'https://varelioolivaforestal.com.ar', 'pyme', 'Global Invest', ''),
  ('(sin nombre en el listado) admin', 'Transporte y logística', 'Garupá', 'admin@rutasmisioneras.net', null, 'pyme', 'Global Invest', ''),
  ('Expreso Taragüí', 'Transporte y logística', 'Garupá', 'administracion@expresotaragui.com.ar', null, 'pyme', 'Global Invest', ''),
  ('GRANJA LA LECHUZA', 'Turismo aventura', 'General Alvear', 'granjalalechuza@gmail.com', null, 'pyme', 'Registro turismo', ''),
  ('El Cruce FB S.R.L', 'Té', 'General Alvear', 'elcrucefbsrl@gmail.com', null, 'pyme', 'Global Invest', ''),
  ('HPT S.R.L', 'Té', 'Guaraní', 'carlos.barbaro@hptsrl.com.ar', null, 'pyme', 'Global Invest', ''),
  ('MURNER DARIO CARLOS', 'Comercio / ferretería / agro', 'Jardín América', 'dariocarlosmurner@yahoo.com.ar', null, 'pyme', 'Rumbo', ''),
  ('Bongers Roberto Juan', 'Transporte y logística', 'Jardín América', 'misionmaderas@gmail.com', null, 'pyme', 'Global Invest', ''),
  ('Caballero Mario Eduardo', 'Transporte y logística', 'Jardín América', 'fenix13.mc@gmail.com', null, 'pyme', 'Global Invest', ''),
  ('Hoffmann Raúl Orlando', 'Transporte y logística', 'Jardín América', 'hoffmannraul@gmail.com', null, 'pyme', 'Global Invest', ''),
  ('Inteq equipamiento industrial', 'Comercio / ferretería / agro', 'Leandro N. Alem', 'inteq.info@gmail.com', null, 'pyme', 'Rumbo', ''),
  ('MCK Bosque y jardin - Koczuk', 'Comercio / ferretería / agro', 'Leandro N. Alem', 'motocarkoczuk@nodoalem.com.ar', null, 'pyme', 'Rumbo', ''),
  ('Constructora K&K S.R.L', 'Construcción', 'Leandro N. Alem', 'juankikue@gmail.com', 'https://arquitecturakikue.com.ar', 'pyme', 'Global Invest', ''),
  ('Dimadera S.R.L', 'Forestal / maderera', 'Leandro N. Alem', 'juriscont@hotmail.com.ar', 'https://www.dimadera.com.ar', 'pyme', 'Global Invest', ''),
  ('Adolfo Sartori S.A.', 'Transporte y logística', 'Leandro N. Alem', 'info@adolfosartorisa.com.ar', null, 'pyme', 'Global Invest', ''),
  ('Díaz Méndez Diego Her.', 'Transporte y logística', 'Leandro N. Alem', 'ddiazmendez@roddar.com.ar', null, 'pyme', 'Global Invest', ''),
  ('Ruzak Ernesto Bernardo', 'Transporte y logística', 'Leandro N. Alem', 'recepcion.transruzak@gmail.com', null, 'pyme', 'Global Invest', ''),
  ('Transporte Goichik S.R.L.', 'Transporte y logística', 'Leandro N. Alem', 'transportegoichiksrl@hotmail.com', null, 'pyme', 'Global Invest', ''),
  ('Werner Luisa', 'Transporte y logística', 'Leandro N. Alem', 'transporte_am@hotmail.com', null, 'pyme', 'Global Invest', ''),
  ('Sergio Moya', 'Turismo aventura', 'Leandro N. Alem', 'sergio.selva.aves@gmail.com', null, 'pyme', 'Registro turismo', ''),
  ('Infusiones Naturales S.R.L', 'Té', 'Leandro N. Alem', 'infoinfusionesnaturales@gmail.com', 'https://www.jesper.com.ar', 'pyme', 'Global Invest', ''),
  ('Envasando S.R.L', 'Yerba mate', 'Leandro N. Alem', 'vaninalew@envasando.com.ar', 'https://www.envasando.com.ar', 'pyme', 'Global Invest', ''),
  ('Tea Wind', 'Té', 'Los Helechos', 'taro747@hotmail.com', null, 'pyme', 'Catálogo té', ''),
  ('WK1', 'Té', 'Los Helechos', 'administracion@wk1sa.com', 'https://wk1sa.com', 'pyme', 'Global Invest', ''),
  ('Karadya Birding Lodge', 'Hotel / lodge', 'Misiones', 'info@karadya.com.ar', 'https://karadya.com.ar', 'pyme', 'Sitio oficial', ''),
  ('Respirar', 'Turismo', 'Misiones', 'info@respirar.tur.ar', 'https://respirar.tur.ar', 'pyme', 'Sitio oficial', ''),
  ('AB BIKE TOUR & Jungle Bike', 'Turismo aventura', 'Misiones', 'andresbordon2020@gmail.com', null, 'pyme', 'Registro turismo', ''),
  ('Camino y Selva', 'Turismo aventura', 'Misiones', 'maurobiolatto5@gmail.com', null, 'pyme', 'Registro turismo', ''),
  ('Campo San Expedito', 'Turismo aventura', 'Misiones', 'c75duarte@gmail.com', null, 'pyme', 'Registro turismo', ''),
  ('Cerne Vida y Monte', 'Turismo aventura', 'Misiones', 'cernevidaymonte@gmail.com', null, 'pyme', 'Registro turismo', ''),
  ('Cueva Miní', 'Turismo aventura', 'Misiones', 'bubynolde@gmail.com', null, 'pyme', 'Registro turismo', ''),
  ('Expediciones Yaboti', 'Turismo aventura', 'Misiones', 'terradiego29@gmail.com', null, 'pyme', 'Registro turismo', ''),
  ('KAYAK DEL SOL – LEG. Nº', 'Turismo aventura', 'Misiones', 'kayakdelsol@gmail.com', null, 'pyme', 'Registro turismo', ''),
  ('Mandioca Turismo Aventura', 'Turismo aventura', 'Misiones', 'mandioca.aventura@gmail.com', null, 'pyme', 'Registro turismo', ''),
  ('Verdagua Evt', 'Turismo aventura', 'Misiones', 'turismoverdagua@gmail.com', null, 'pyme', 'Registro turismo', ''),
  ('Té Cachamai', 'Té', 'Misiones', 'atencionalconsumidor@cachamai.com', 'https://cachamai.com.ar', 'pyme', 'Sitio oficial', ''),
  ('Yerba Mate Anna Park', 'Yerba mate', 'Misiones', 'annaparkyerbamate@gmail.com', 'https://annapark.com.ar', 'pyme', 'Sitio oficial', ''),
  ('Yerbatera Hoja Verde', 'Yerba mate', 'Misiones', 'contacto@yerbaterahojaverde.com', 'https://yerbaterahojaverde.com', 'pyme', 'Sitio oficial', ''),
  ('ALFA FERRETERIA - Schieffer Fernando Emanuel', 'Comercio / ferretería / agro', 'Montecarlo', 'alfapintur@yahoo.com.ar', null, 'pyme', 'Rumbo', ''),
  ('BOCHERT ALFREDO ARNOLDO', 'Comercio / ferretería / agro', 'Montecarlo', 'agropecuariadonpancho@hotmail.com.ar', null, 'pyme', 'Rumbo', ''),
  ('Coop. Agricola Monte Carlo', 'Comercio / ferretería / agro', 'Montecarlo', 'cbergmeier@aguantadora.com', null, 'pyme', 'Rumbo', ''),
  ('Denis Alfredo Bochert', 'Forestal / maderera', 'Montecarlo', 'ronnybochert@gmail.com', null, 'pyme', 'Global Invest', ''),
  ('Taeda S.A', 'Forestal / maderera', 'Montecarlo', 'taeda@taedasa.com.ar', 'https://taedasa.com.ar', 'grande', 'Global Invest', ''),
  ('Cooperativa Agrícola Mixta de Montecarlo Ltda.', 'Yerba mate', 'Montecarlo', 'carntzen@montecarlo.com.ar', 'https://www.montecarlo.com.ar', 'pyme', 'Global Invest', ''),
  ('Andersson Richard Leonardo', 'Comercio / ferretería / agro', 'Oberá', 'anderssonmaquinarias@hotmail.com', null, 'pyme', 'Rumbo', ''),
  ('Himpa SRL', 'Comercio / ferretería / agro', 'Oberá', 'electricidadobera@hotmail.com', null, 'pyme', 'Rumbo', ''),
  ('Dexim S.R.L', 'Comercio exterior', 'Oberá', 'federicoplotz@deximsrl.com', 'https://www.dexim.com.ar', 'pyme', 'Global Invest', ''),
  ('Zecchini Guido', 'Despachante de aduana', 'Oberá', 'gzecchini@estudiocipe.com.ar', null, 'pyme', 'Global Invest', ''),
  ('Nordica S.A', 'Forestal / maderera', 'Oberá', 'ventasnordicasa@gmail.com', null, 'pyme', 'Global Invest', ''),
  ('Hotel Casino Oberá', 'Hotel', 'Oberá', 'casinooberahotel@gmail.com', 'https://hotelcasinoobera.com.ar', 'pyme', 'Sitio oficial', ''),
  ('El Ultimo Grito Aventuras', 'Turismo aventura', 'Oberá', 'walterturismo@gmail.com', null, 'pyme', 'Registro turismo', ''),
  ('Misiones Off Road', 'Turismo aventura', 'Oberá', 'lreguera777@gmail.com', null, 'pyme', 'Registro turismo', ''),
  ('Monte Aventura', 'Turismo aventura', 'Oberá', 'monteavent@yahoo.com.ar', null, 'pyme', 'Registro turismo', ''),
  ('Rappel Misiones', 'Turismo aventura', 'Oberá', 'javsal644@hotmail.com', null, 'pyme', 'Registro turismo', ''),
  ('Tekoha Aventuras', 'Turismo aventura', 'Oberá', 'tekohaaventura@gmail.com', null, 'pyme', 'Registro turismo', ''),
  ('Casa Fuentes SACIFI', 'Té', 'Oberá', 'diego.solleveld@finlays.net', 'https://www.finlays.net', 'grande', 'Global Invest', ''),
  ('Del Iguazú Infusiones', 'Té', 'Oberá', 'pablo@tedemisiones.com', null, 'pyme', 'Listado web', 'Email sin verificar en el sitio de la empresa.'),
  ('Don Eduardo S.R.L', 'Té', 'Oberá', 'info@doneduardosrl.com.ar', 'https://www.doneduardosrl.com.ar', 'pyme', 'Global Invest', ''),
  ('Hebras Misioneras', 'Té', 'Oberá', 'hebrasmisioneras@gmail.com', null, 'pyme', 'Listado web', 'Email sin verificar en el sitio de la empresa.'),
  ('Kairiyama', 'Té', 'Oberá', 'tekairiyama@yahoo.com', null, 'pyme', 'Catálogo té', ''),
  ('La Ruta del Té', 'Té', 'Oberá', 'ventas@larutadelte.com.ar', null, 'pyme', 'Listado web', 'Email sin verificar en el sitio de la empresa.'),
  ('Las Treinta S.A', 'Té', 'Oberá', 'contacto@lastreinta.com.ar', 'https://lastreinta.com.ar', 'pyme', 'Global Invest', ''),
  ('Amsa S.R.L', 'Yerba mate', 'Oberá', 'administracion@molinosanmiguel.com.ar', 'https://www.molinosanmiguel.com.ar', 'pyme', 'Global Invest', ''),
  ('Don Basilio S.R.L', 'Yerba mate', 'Oberá', 'okulovichc@donbasilio.com.ar', 'https://www.donbasilio.com', 'pyme', 'Global Invest', ''),
  ('J.S S.A', 'Yerba mate', 'Oberá', 'info@materojo.com.ar', 'https://www.grupomaterojo.com.ar', 'pyme', 'Global Invest', ''),
  ('Soc. Arg. Para nuevos Emprendedores S.A', 'Yerba mate', 'Oberá', 'hercorchemes@sanesa.com.ar', 'https://www.yerbanatura.com.ar', 'pyme', 'Global Invest', ''),
  ('Aserradero Jeske S.R.L', 'Forestal / maderera', 'Panambi', 'estudioostratiuk@hotmail.com', 'https://aserraderojeske.com.ar', 'pyme', 'Global Invest', ''),
  ('Drisner Hermanos S.A', 'Forestal / maderera', 'Panambi', 'drisner@estudiofritsche.com.ar', null, 'pyme', 'Global Invest', ''),
  ('Mi Reserva', 'Agencia de viajes', 'Posadas', 'ventas1@mireserva.tur.ar', 'https://mireserva.tur.ar', 'pyme', 'Sitio oficial', ''),
  ('Misiones Maravilla', 'Agencia de viajes', 'Posadas', 'info@misionesmaravilla.com', 'https://misionesmaravilla.com', 'pyme', 'Sitio oficial', ''),
  ('Transrío Turismo', 'Agencia de viajes', 'Posadas', 'info@transrioturismo.tur.ar', 'https://transrioturismo.tur.ar', 'pyme', 'Sitio oficial', ''),
  ('Bulonera Posadas SRL', 'Comercio / ferretería / agro', 'Posadas', 'buloneraposadas@yahoo.com.ar', null, 'pyme', 'Rumbo', ''),
  ('Ferretería Aguilar (Tienda Grupo Rumbo)', 'Comercio / ferretería / agro', 'Posadas', 'ventas@ferreteriaaguilar.com.ar', null, 'pyme', 'Rumbo', ''),
  ('Ferromisiones SRL', 'Comercio / ferretería / agro', 'Posadas', 'ferromisiones.adm@gmail.com', null, 'pyme', 'Rumbo', ''),
  ('Nativa Forestal', 'Comercio / ferretería / agro', 'Posadas', 'ferreteria@nativaforestal.com.ar', null, 'pyme', 'Rumbo', ''),
  ('NUSCAA SAS - Ferretería Sur', 'Comercio / ferretería / agro', 'Posadas', 'alvez_fernando@gmail.com', null, 'pyme', 'Rumbo', ''),
  ('Sinergia Industrial SRL', 'Comercio / ferretería / agro', 'Posadas', 'compras@sinergiaindustrial.com.ar', null, 'pyme', 'Rumbo', ''),
  ('Lug Argentina S.A', 'Construcción', 'Posadas', 'fdominguez@lug.com.ar', 'https://luglightfactory.com', 'grande', 'Global Invest', ''),
  ('Abel Lugo', 'Despachante de aduana', 'Posadas', 'abel@despachantesaduaneros.com', null, 'pyme', 'Global Invest', ''),
  ('Albracht Soler SRL', 'Despachante de aduana', 'Posadas', 'patriciaalbracht@albrachtsolersrl.com.ar', null, 'pyme', 'Global Invest', ''),
  ('ERNESTO SEIDEL', 'Despachante de aduana', 'Posadas', 'ernestojjseidel@gmail.com', null, 'pyme', 'Global Invest', ''),
  ('Fiori Javier', 'Despachante de aduana', 'Posadas', 'javierrjrfiori@gmail.com', null, 'pyme', 'Global Invest', ''),
  ('Gonzalo Landi', 'Despachante de aduana', 'Posadas', 'gonzalo@go-comex.com', null, 'pyme', 'Global Invest', ''),
  ('JUAN CARLOS DUBLECE NETTO', 'Despachante de aduana', 'Posadas', 'juankdublecenetto@gmail.com', null, 'pyme', 'Global Invest', ''),
  ('Llamas José', 'Despachante de aduana', 'Posadas', 'llamasdespachantedeaduana@gmail.com', null, 'pyme', 'Global Invest', ''),
  ('Universal Logística S.A.', 'Despachante de aduana', 'Posadas', 'rubenalmiron@universallogistic.com.ar', null, 'pyme', 'Global Invest', ''),
  ('Universidad Católica de Santa Fe – sede Posadas', 'Educación', 'Posadas', 'institucional@ucsf.edu.ar', 'https://ucsf.edu.ar', 'pyme', 'Sitio oficial', ''),
  ('Forestal Guarani S.A', 'Forestal / maderera', 'Posadas', 'forestalguaranisa@gmail.com', 'https://www.forestalguarani.com', 'pyme', 'Global Invest', ''),
  ('Continental Posadas Hotel', 'Hotel', 'Posadas', 'reservas@continentalposadashotel.com', 'https://continentalposadashotel.com', 'pyme', 'Sitio oficial', ''),
  ('Hotel Posadas', 'Hotel', 'Posadas', 'reservas@hotelposadas.com.ar', 'https://hotelposadas.com.ar', 'pyme', 'Sitio oficial', ''),
  ('La Misión Posadas Hotel', 'Hotel', 'Posadas', 'lamisionposadas@gmail.com', 'https://lamisionposadashotel.com', 'pyme', 'Sitio oficial', ''),
  ('Frida Boutique', 'Indumentaria', 'Posadas', 'fridaposadas1@gmail.com', 'https://frida.com.ar', 'pyme', 'Sitio oficial', ''),
  ('Paradise Posadas', 'Indumentaria', 'Posadas', 'paradiseposadas@gmail.com', 'https://paradiseposadas.com.ar', 'pyme', 'Sitio oficial', ''),
  ('Cámara de Comercio e Industria de Posadas', 'Institución', 'Posadas', 'camaracomercioccip@gmail.com', 'https://ccip.com.ar', 'pyme', 'Sitio oficial', ''),
  ('Hidra S.R.L', 'Metalmecánica', 'Posadas', 'marielam@activosrl.com.ar', 'https://estancco.com', 'pyme', 'Global Invest', ''),
  ('Metalurgica Hañiek S.A', 'Metalmecánica', 'Posadas', 'metalurgicahaniek@gmail.com', 'https://www.metalurgicahaniek.com.ar', 'pyme', 'Global Invest', ''),
  ('Tecnometal', 'Metalmecánica', 'Posadas', 'adm@tecnometalmisiones.com.ar', 'https://tecnometalmisiones.com.ar', 'pyme', 'Global Invest', ''),
  ('Pinturas Misioneras', 'Pinturas / comercio', 'Posadas', 'central@pinturas-misioneras.com.ar', 'https://pinturasmisioneras.com.ar', 'pyme', 'Sitio oficial', ''),
  ('Sanatorio Boratti', 'Salud', 'Posadas', 'secretaria@boratti.com.ar', 'https://sanatorioboratti.com.ar', 'pyme', 'Sitio oficial', ''),
  ('Grupo Vicnet S.R.L', 'Servicios', 'Posadas', 'lhorrisberger@vicnet.com.ar', 'https://www.vicnet.com.ar', 'pyme', 'Global Invest', ''),
  ('MED Industrial', 'Textil', 'Posadas', 'info@medindustrial.com.ar', 'https://www.medindustrial.com.ar', 'pyme', 'Global Invest', ''),
  ('Obrera', 'Textil', 'Posadas', 'ventas.obrera@missiongroupsrl.com.ar', 'https://www.obrera.ar', 'pyme', 'Global Invest', ''),
  ('TEX Industrial', 'Textil', 'Posadas', 'ventas@missiongroupsrl.com.ar', 'https://www.texindustrial.com.ar', 'pyme', 'Global Invest', ''),
  ('Misiones Fly', 'Turismo aventura', 'Posadas', 'mauricioripoll75@gmail.com', null, 'pyme', 'Registro turismo', ''),
  ('Sergio Balatorre Aventuras', 'Turismo aventura', 'Posadas', 'sergiobalatorreav@gmail.com', null, 'pyme', 'Registro turismo', ''),
  ('Skytopia', 'Turismo aventura', 'Posadas', 'ale.somm@gmail.com', null, 'pyme', 'Registro turismo', ''),
  ('Aromas de la Selva', 'Té', 'Posadas', 'clforastier@gmail.com', null, 'pyme', 'Catálogo té', ''),
  ('Infusiones Dana', 'Té', 'Posadas', 'infusionesdana@gmail.com', null, 'pyme', 'Catálogo té', ''),
  ('La Francisca Casa de Té', 'Té', 'Posadas', 'lafranciscacasadete@gmail.com', null, 'pyme', 'Catálogo té', ''),
  ('Zoco Tea Bar', 'Té', 'Posadas', 'zocodelimarket@gmail.com', null, 'pyme', 'Catálogo té', ''),
  ('Kraus S.A', 'Yerba mate', 'Posadas', 'kraus@kraus.com.ar', 'https://www.kraus.com.ar', 'pyme', 'Global Invest', ''),
  ('La Cachuera S.A', 'Yerba mate', 'Posadas', 'comex@amanda.com.ar', 'https://tienda.yerbamanda.com.ar', 'pyme', 'Global Invest', ''),
  ('Depimiel S.R.L', 'Forestal / maderera', 'Profundidad', 'federico@depimiel.com', 'https://www.depimielforestal.com', 'pyme', 'Global Invest', ''),
  ('Pindo S.A', 'Forestal / maderera', 'Puerto Esperanza', 'jose@pindosa.com.ar', 'https://pindosa.com.ar', 'grande', 'Global Invest', ''),
  ('Reemix Tur', 'Agencia de viajes', 'Puerto Iguazú', 'ventas@reemix.tur.ar', 'https://reemix.tur.ar', 'pyme', 'Sitio oficial', ''),
  ('Florentin e Hijos SRL', 'Comercio / ferretería / agro', 'Puerto Iguazú', 'florymotosiguazu@gmail.com', null, 'pyme', 'Rumbo', ''),
  ('Mattos Jorge Rudy', 'Comercio / ferretería / agro', 'Puerto Iguazú', 'agrovet-layapa@hotmail.com', null, 'pyme', 'Rumbo', ''),
  ('ALVARADO FLORENCIA', 'Despachante de aduana', 'Puerto Iguazú', 'florencia@alvaradosrl.com', null, 'pyme', 'Global Invest', ''),
  ('RODOLFO FABIÁN GOYA', 'Despachante de aduana', 'Puerto Iguazú', 'rudyfabian@hotmail.com', null, 'pyme', 'Global Invest', ''),
  ('SERGIO R. SPALLANZANI', 'Despachante de aduana', 'Puerto Iguazú', 'sergio@rioiguazusrl.com.ar', null, 'pyme', 'Global Invest', ''),
  ('Sosa Marchese Mdes.', 'Despachante de aduana', 'Puerto Iguazú', 'marchesesosa@gmail.com', null, 'pyme', 'Global Invest', ''),
  ('Amerian Portal del Iguazú', 'Hotel', 'Puerto Iguazú', 'info@amerian.com', 'https://amerian.com', 'grande', 'Sitio oficial', ''),
  ('Awasi Iguazú', 'Hotel', 'Puerto Iguazú', 'info@awasi.com', 'https://awasi.com', 'grande', 'Sitio oficial', ''),
  ('El Pueblito Hotel Temático', 'Hotel', 'Puerto Iguazú', 'reservas@elpueblitoiguazu.com', 'https://elpueblitoiguazu.com', 'pyme', 'Sitio oficial', ''),
  ('Fortín Cataratas', 'Hotel', 'Puerto Iguazú', 'ventas@grupobordin.com', 'https://fortincataratas.com', 'pyme', 'Sitio oficial', ''),
  ('Gran Hotel Tourbillon', 'Hotel', 'Puerto Iguazú', 'reservas@granhoteltourbillon.com.ar', 'https://granhoteltourbillon.org.ar', 'pyme', 'Sitio oficial', ''),
  ('Guaminí Misión Hotel', 'Hotel', 'Puerto Iguazú', 'reservas@hotelguamini.com.ar', 'https://hotelguamini.com.ar', 'pyme', 'Sitio oficial', ''),
  ('Hotel Falls Iguazú', 'Hotel', 'Puerto Iguazú', 'reservas@hotelfallsiguazu.com', 'https://hotelfallsiguazu.com', 'pyme', 'Sitio oficial', ''),
  ('Hotel Raíces Esturión / Esturión', 'Hotel', 'Puerto Iguazú', 'info@raicesdelplata.com', 'https://raicesesturion.com', 'pyme', 'Sitio oficial', ''),
  ('Hotel Saint George', 'Hotel', 'Puerto Iguazú', 'info@hotelsaintgeorge.com', 'https://hotelsaintgeorge.com', 'pyme', 'Sitio oficial', ''),
  ('Hotel Village Cataratas', 'Hotel', 'Puerto Iguazú', 'info@villagecataratas.com', 'https://villagecataratas.com', 'pyme', 'Sitio oficial', ''),
  ('Iguazú Grand / Panoramic Grand', 'Hotel', 'Puerto Iguazú', 'reserveigr@grand-hotels-lux.com', 'https://iguazugrand.com', 'grande', 'Sitio oficial', ''),
  ('Loi Suites Iguazú', 'Hotel', 'Puerto Iguazú', 'iguazu@loisuites.com.ar', 'https://loisuites.com.ar', 'pyme', 'Sitio oficial', ''),
  ('O2 Hotel Iguazú', 'Hotel', 'Puerto Iguazú', 'reservas1@grupodotia.com', 'https://o2hoteliguazu.com', 'pyme', 'Sitio oficial', ''),
  ('Pirayú Hotel & Resort', 'Hotel', 'Puerto Iguazú', 'reservas@pirayu.com.ar', 'https://pirayu.com.ar', 'pyme', 'Sitio oficial', ''),
  ('Posada Puerto Bemberg', 'Hotel', 'Puerto Iguazú', 'info@posadapuertobemberg.com', 'https://posadapuertobemberg.com', 'pyme', 'Sitio oficial', ''),
  ('Iguazú Jungle Lodge', 'Hotel / lodge', 'Puerto Iguazú', 'reservas@iguazujunglehotel.com', 'https://iguazujunglelodge.com', 'pyme', 'Sitio oficial', ''),
  ('La Aldea de la Selva Lodge', 'Hotel / lodge', 'Puerto Iguazú', 'info@laaldeadelaselva.com', 'https://laaldeadelaselva.com', 'pyme', 'Sitio oficial', ''),
  ('La Reserva Virgin Lodge', 'Hotel / lodge', 'Puerto Iguazú', 'reservas@lareservavirginlodge.com', 'https://lareservavirginlodge.com', 'pyme', 'Sitio oficial', ''),
  ('Selvaje Lodge Iguazú', 'Hotel / lodge', 'Puerto Iguazú', 'selvaje@reservadirecto.com', 'https://selvajelodge.com', 'pyme', 'Sitio oficial', ''),
  ('Tierra Guaraní Lodge de Selva', 'Hotel / lodge', 'Puerto Iguazú', 'tierraguaranilodge@gmail.com', 'https://tierraguaranilodge.com', 'pyme', 'Sitio oficial', ''),
  ('Yacutinga Lodge', 'Hotel / lodge', 'Puerto Iguazú', 'yacutinga@yacutinga.com', 'https://yacutinga.com', 'pyme', 'Sitio oficial', ''),
  ('Iguazú Convention Bureau', 'Institución', 'Puerto Iguazú', 'convention@iguazuconventionbureau.com', 'https://iguazuconventionbureau.com', 'pyme', 'Sitio oficial', ''),
  ('Supermercado Tío Juan', 'Supermercado', 'Puerto Iguazú', 'tiojuansupermercado@gmail.com', 'https://supermercadotiojuan.com', 'pyme', 'Listado web', 'Email sin verificar en el sitio de la empresa.'),
  ('Supermercado Tío Juan (2º contacto)', 'Supermercado', 'Puerto Iguazú', 'guilleoscarb@hotmail.com', 'https://supermercadotiojuan.com', 'pyme', 'Listado web', 'Email sin verificar en el sitio de la empresa.'),
  ('Iguazú Argentina (Cataratas)', 'Turismo', 'Puerto Iguazú', 'info@iguazuargentina.com', 'https://iguazuargentina.com', 'pyme', 'Sitio oficial', ''),
  ('Iguazú Jungle Explorer', 'Turismo', 'Puerto Iguazú', 'info@iguazujungle.com', 'https://iguazujungle.com', 'pyme', 'Sitio oficial', ''),
  ('La Aripuca', 'Turismo', 'Puerto Iguazú', 'info@aripuca.com.ar', 'https://aripuca.com.ar', 'pyme', 'Sitio oficial', ''),
  ('Güirá Oga (Fundación Azara)', 'Turismo / conservación', 'Puerto Iguazú', 'guiraoga@fundacionazara.org.ar', 'https://guiraoga.com.ar', 'pyme', 'Sitio oficial', ''),
  ('Iguazú Bike Tours', 'Turismo aventura', 'Puerto Iguazú', 'info@iguazubiketours.com.ar', null, 'pyme', 'Registro turismo', ''),
  ('Iguazú Kayak', 'Turismo aventura', 'Puerto Iguazú', 'iguazukayak@gmail.com', null, 'pyme', 'Registro turismo', ''),
  ('Maravillas del Té', 'Té', 'Puerto Iguazú', 'maravillasdelte@gmail.com', null, 'pyme', 'Catálogo té', ''),
  ('Papel Misionero SAIFC', 'Industria', 'Puerto Leoni', 'igoldentair@arcor.com', 'https://www.cartocor.com', 'grande', 'Global Invest', ''),
  ('Emilio White', 'Turismo aventura', 'Puerto Libertad', 'manakin@gmail.com', null, 'pyme', 'Registro turismo', ''),
  ('La Lorenza', 'Turismo aventura', 'Puerto Libertad', 'info@lalorenzaiguazu.com', null, 'pyme', 'Registro turismo', ''),
  ('Urugua-Í En Kayak', 'Turismo aventura', 'Puerto Libertad', 'uruguai.en.kayak@gmail.com', null, 'pyme', 'Registro turismo', ''),
  ('Electricidad Botz - Botz Roberto', 'Comercio / ferretería / agro', 'Puerto Rico', 'robertobotz@gmail.com', null, 'pyme', 'Rumbo', ''),
  ('Aserradero San Alberto', 'Forestal / maderera', 'Puerto Rico', 'aserraderosanalberto@gmail.com', null, 'pyme', 'Global Invest', ''),
  ('Puerto Maderas S.R.L', 'Forestal / maderera', 'Puerto Rico', 'puertomaderas@prico.com.ar', null, 'pyme', 'Global Invest', ''),
  ('Ruberlac S.A', 'Forestal / maderera', 'Puerto Rico', 'ruberlacsa1986@gmail.com', null, 'pyme', 'Global Invest', ''),
  ('Cooperativa Agrícola de Ruiz de Montoya (Tucanguá)', 'Cooperativa agrícola', 'Ruiz de Montoya', 'coop_tucangua@prico.com.ar', null, 'pyme', 'Listado web', 'Email sin verificar en el sitio de la empresa.'),
  ('Agropecuaria Ale - ALE-BAR SRL', 'Comercio / ferretería / agro', 'Salto Encantado', 'finkenbarbara936@gmail.com', null, 'pyme', 'Rumbo', ''),
  ('Bar Eugenio Omar', 'Gastronomía', 'Salto Encantado', 'casatigrese@gmail.com', null, 'pyme', 'Rumbo', ''),
  ('Experiencias del Salto', 'Turismo aventura', 'Salto Encantado', 'clarisareinaldo1@gmail.com', null, 'pyme', 'Registro turismo', ''),
  ('Grondona Paulo Roberto', 'Comercio / ferretería / agro', 'San Antonio', 'grondonapablo@gmail.com', null, 'pyme', 'Rumbo', ''),
  ('Kraucos', 'Comercio / ferretería / agro', 'San Antonio', 'kraucos@hotmail.com', null, 'pyme', 'Rumbo', ''),
  ('Calhuem Naturaleza Con Alma', 'Turismo aventura', 'San Ignacio', 'calhuemsrl@gmail.com', null, 'pyme', 'Registro turismo', ''),
  ('Andersson S.A.', 'Comercio / ferretería / agro', 'San Javier', 'andersasanjavier@gmail.com', null, 'pyme', 'Rumbo', ''),
  ('Alarcón Emanuel', 'Despachante de aduana', 'San Javier', 'alarcondespachosaduaneros@hotmail.com', null, 'pyme', 'Global Invest', ''),
  ('Busse Mercedes', 'Despachante de aduana', 'San Javier', 'mariadelasmercedesbusse@gmail.com', null, 'pyme', 'Global Invest', ''),
  ('Carratini Sebastián', 'Despachante de aduana', 'San Javier', 'sebastian@estudiocarratini.com.ar', null, 'pyme', 'Global Invest', ''),
  ('Didolich Adrian Cayetano', 'Despachante de aduana', 'San Javier', 'adriandidolich@hotmail.com', null, 'pyme', 'Global Invest', ''),
  ('Núñez Gerardo', 'Despachante de aduana', 'San Javier', 'gerardonunez2007@hotmail.com', null, 'pyme', 'Global Invest', ''),
  ('Renedo Luis F.', 'Despachante de aduana', 'San Javier', 'rys.luisrenedo@gmail.com', null, 'pyme', 'Global Invest', ''),
  ('Schmechel Elisa E.', 'Despachante de aduana', 'San Javier', 'elisaschmechel@hotmail.com', null, 'pyme', 'Global Invest', ''),
  ('Stragevich Nancy Andrea', 'Despachante de aduana', 'San Javier', 'nastrag@hotmail.com', null, 'pyme', 'Global Invest', ''),
  ('Akashá Tea', 'Té', 'San Javier', 'akashateaargentina@gmail.com', null, 'pyme', 'Listado web', 'Email sin verificar en el sitio de la empresa.'),
  ('Kolodziej Alicia', 'Comercio / ferretería / agro', 'San Pedro', 'lubrigas30@gmail.com', null, 'pyme', 'Rumbo', ''),
  ('Total Agroinsumos SAS', 'Comercio / ferretería / agro', 'San Pedro', 'totalinsumosagro@gmail.com', null, 'pyme', 'Rumbo', ''),
  ('Yerba Mate Herencia', 'Yerba mate', 'San Pedro', 'yerbamateherencia@gmail.com', 'https://yerbamateherencia.com.ar', 'pyme', 'Sitio oficial', ''),
  ('5 Hermanos Electrodomésticos - Grupo Lorenzo SRL', 'Comercio / ferretería / agro', 'San Vicente', 'grupolorenzo@hotmail.com', null, 'pyme', 'Rumbo', ''),
  ('Diedrich Noemi L.', 'Comercio / ferretería / agro', 'San Vicente', 'todomotos_sv@hotmail.com', null, 'pyme', 'Rumbo', ''),
  ('Grandes Bosques S.R.L', 'Forestal / maderera', 'San Vicente', 'grandesbosquesssrl@hotmail.com', null, 'pyme', 'Global Invest', ''),
  ('Placas Centro S.R.L', 'Forestal / maderera', 'San Vicente', 'placascentro.ad@gmail.com', 'https://www.placascentro.com', 'pyme', 'Global Invest', ''),
  ('El Maynó', 'Gastronomía', 'Santa Ana', 'hola@elmayno.com', 'https://elmayno.com', 'pyme', 'Sitio oficial', ''),
  ('Piporé S.C.L', 'Yerba mate', 'Santo Pipó', 'sleguia@pipore.com.ar', 'https://www.pipore.com.ar', 'pyme', 'Global Invest', ''),
  ('Yerba Mate Federal', 'Yerba mate', 'Santo Pipó', 'yerbamatefederal@gmail.com', 'https://yerbamatefederal.com.ar', 'pyme', 'Sitio oficial', ''),
  ('Yerba Mate Piporé', 'Yerba mate', 'Santo Pipó', 'info@pipore.com.ar', 'https://pipore.com.ar', 'pyme', 'Sitio oficial', ''),
  ('(sin nombre en el listado) transgruber1e', 'Transporte y logística', 'Wanda', 'transgruber1e@arnet.com.ar', null, 'pyme', 'Global Invest', ''),
  ('Calvo Juan Carlos', 'Transporte y logística', 'Wanda', 'cincuenca@hotmail.com', null, 'pyme', 'Global Invest', ''),
  ('Espinoza Inocencio', 'Transporte y logística', 'Wanda', 'susanaespinoza15@gmail.com', null, 'pyme', 'Global Invest', ''),
  ('Jelen Andrea', 'Transporte y logística', 'Wanda', 'andreajelen1@yahoo.com.ar', null, 'pyme', 'Global Invest', ''),
  ('Jelen Pedro Raúl', 'Transporte y logística', 'Wanda', 'raul@ejewan.com.ar', null, 'pyme', 'Global Invest', ''),
  ('Jeleñ Germán Emanuel', 'Transporte y logística', 'Wanda', 'germanjelen@tupiena.com.ar', null, 'pyme', 'Global Invest', ''),
  ('Mayerhofer Cristian Omar', 'Transporte y logística', 'Wanda', 'cmayerhofer496@gmail.com', null, 'pyme', 'Global Invest', ''),
  ('Moreira Roberto Ariel', 'Transporte y logística', 'Wanda', 'robertoarielmoreira@gmail.com', null, 'pyme', 'Global Invest', ''),
  ('Skiba Casimiro', 'Transporte y logística', 'Wanda', 'transporteskiba@hotmail.com', null, 'pyme', 'Global Invest', '')
on conflict (email) do nothing;
